# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='treatment_name',
            field=models.CharField(max_length=100),
        ),
    ]
