# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-15 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_site', '0002_auto_20170114_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='treatment_descripton',
            field=models.TextField(null=True),
        ),
    ]
